In [1]:
import pandas as pd

In [2]:
df_state_ratio=pd.read_csv('./datas/h1b_train_ratio.csv',keep_default_na=False)
df_soccode_ratio=pd.read_csv('./datas/soccode_with_ratio.csv',keep_default_na=False)

In [43]:
file_path='./datas/'
file_name=file_path+"h1b_train_preprocessing.csv"
df=pd.read_csv(file_name,keep_default_na=False)

In [13]:
df_state_ratio=df_state_ratio.drop("CERTIFIED",axis=1)
df_state_ratio=df_state_ratio.drop("DENIED",axis=1)

                 STATE     ratio
0              ALABAMA  0.063939
1               ALASKA  0.148970
2              ARIZONA  0.031144
3             ARKANSAS  0.024332
4           CALIFORNIA  0.036592
5             COLORADO  0.040225
6          CONNECTICUT  0.027713
7             DELAWARE  0.022649
8   DISTRICTOFCOLUMBIA  0.061583
9              FLORIDA  0.059659
10             GEORGIA  0.030453
11              HAWAII  0.124794
12               IDAHO  0.049831
13            ILLINOIS  0.027655
14             INDIANA  0.032534
15                IOWA  0.031150
16              KANSAS  0.035937
17            KENTUCKY  0.037739
18           LOUISIANA  0.062704
19               MAINE  0.031500
20            MARYLAND  0.043691
21       MASSACHUSETTS  0.035775
22            MICHIGAN  0.030233
23           MINNESOTA  0.025562
24         MISSISSIPPI  0.081006
25            MISSOURI  0.026818
26             MONTANA  0.098291
27            NEBRASKA  0.034381
28              NEVADA  0.102990
29        NEWHAMPSHIRE  0.025606
30           NEWJERSEY  0.025568
31           NEWMEXICO  0.073692
32             NEWYORK  0.050929
33       NORTHCAROLINA  0.026581
34         NORTHDAKOTA  0.050870
35                OHIO  0.028133
36            OKLAHOMA  0.052371
37              OREGON  0.029119
38        PENNSYLVANIA  0.028404
39          PUERTORICO  0.193410
40         RHODEISLAND  0.023683
41       SOUTHCAROLINA  0.048497
42         SOUTHDAKOTA  0.051051
43           TENNESSEE  0.034217
44               TEXAS  0.033479
45                UTAH  0.053648
46             VERMONT  0.062753
47            VIRGINIA  0.036426
48          WASHINGTON  0.022736
49        WESTVIRGINIA  0.065986
50           WISCONSIN  0.025128
51             WYOMING  0.162602

In [26]:
df_state_ratio=df_state_ratio.set_index('STATE')
ratio_dict=df_state_ratio.to_dict()
ratio_mapping=ratio_dict['ratio']

In [29]:
df['STATE_RATIO']=df['STATE'].map(ratio_mapping)

In [33]:
df_soccode_ratio=df_soccode_ratio.drop("Unnamed: 0",axis=1)
df_soccode_ratio

   SOC_CODE  ratio_soc
0       0o0   0.101452
1    0o1001   0.240000
2    0o1002   0.063996
3    0o1003   0.000000
4    0o1004   0.053905
5    0o1005   0.000000
6    0o1010   0.086915
7    0o1020   0.049732
8    0o1021   0.000000
9    0o1022   0.287081
10   0o1024   0.204819
11   0o1030   0.045211
12   0o1040   0.078756
13   0o1044   0.034114
14   0o1050   0.035727
15   0o1100   0.038878
16   0o1104   0.073351
17   0o1110   0.000000
18   0o1120   0.032944
19   0o1140   0.048218
20   0o1200   0.070015
21   0o1204   0.070748
22   0o1220   0.500000
23   0o1240   0.035714
24   0o1300   0.031334
25   0o1304   0.062125
26   0o1340   0.078313
27   0o1400   0.018209
28   0o1402   0.034884
29   0o1403   0.000000
30   0o1404   0.037085
31   0o1420   0.117162
32   0o1422   0.079724
33   0o1424   0.039106
34   0o1430   0.105698
35   0o1440   0.040961
36   0o1514   0.028350
37   0o1520   0.045455
38   0o1600   0.173913
39   0o1620   0.120215

In [37]:
df_soccode_ratio=df_soccode_ratio.set_index('SOC_CODE')

KeyError: 'SOC_CODE'

In [38]:
soccode_ratio_dict=df_soccode_ratio.to_dict()
soccode_ratio_mapping=soccode_ratio_dict['ratio_soc']

In [39]:
df['SOC_RATIO']=df['SOC_CODE'].map(soccode_ratio_mapping)

In [44]:
df

,CASE_STATUS,FULL_TIME_POSITION,YEAR,SOC_CODE,STATE,WAGE_CATEGORY
0,0,1,2014,0o1400,CALIFORNIA,LOW
1,0,1,2015,0o1400,CALIFORNIA,MEDIUM
2,0,1,2014,0o1400,CALIFORNIA,MEDIUM
3,0,1,2011,0o0,ILLINOIS,LOW
4,1,1,2015,0o1300,CALIFORNIA,VERY LOW
5,0,1,2011,0o1404,CALIFORNIA,MEDIUM
6,0,0,2016,0o1200,CAROLINA,LOW
7,0,1,2012,0o1400,OHIO,HIGH
8,0,1,2011,0o1404,VIRGINIA,LOW
9,0,1,2014,0o1400,CALIFORNIA,HIGH
10,0,1,2013,0o1400,WASHINGTON,MEDIUM
11,0,1,2012,0o1400,CALIFORNIA,HIGH
12,0,1,2014,0o1004,TEXAS,MEDIUM
13,0,1,2013,0o1400,JERSEY,MEDIUM
14,0,1,2011,0o1004,MINNESOTA,LOW
15,0,1,2014,0o1402,CALIFORNIA,LOW
16,0,1,2015,0o1240,TEXAS,HIGH
17,0,1,2011,0o1430,MARYLAND,LOW
18,0,1,2014,0o1400,TEXAS,LOW
19,0,1,2016,0o1400,CALIFORNIA,MEDIUM
20,0,1,2013,0o1400,WASHINGTON,MEDIUM
21,0,1,2012,0o1400,FLORIDA,MEDIUM
22,0,1,2015,0o1400,CALIFORNIA,MEDIUM
23,0,0,2016,0o1010,TEXAS,LOW
24,0,1,2013,0o1004,YORK,VERY LOW
25,0,1,2013,0o1012,YORK,LOW
26,0,1,2011,0o1400,MASSACHUSETTS,LOW
27,1,1,2015,0o1404,CALIFORNIA,LOW
28,0,1,2012,0o1200,PENNSYLVANIA,MEDIUM
29,0,1,2014,0o1400,PENNSYLVANIA,MEDIUM
...,...,...,...,...,...,...
1626857,0,1,2014,0o1021,CALIFORNIA,HIGH
1626858,0,1,2014,0o1002,GEORGIA,VERY LOW
1626859,0,1,2012,0o1400,JERSEY,LOW
1626860,0,1,2015,0o1400,RICO,VERY LOW
1626861,0,1,2016,0o1400,WASHINGTON,HIGH
1626862,0,1,2014,0o1400,TEXAS,MEDIUM
1626863,0,1,2012,0o1400,MASSACHUSETTS,LOW
1626864,0,1,2014,0o1100,KANSAS,VERY LOW
1626865,0,1,2011,0o1040,CAROLINA,VERY LOW
1626866,0,1,2015,0o1400,CALIFORNIA,LOW
1626867,0,1,2014,0o1400,DELAWARE,LOW
1626868,0,0,2016,0o1400,CALIFORNIA,LOW
1626869,0,1,2014,0o1400,OHIO,LOW
1626870,0,1,2011,0o1100,UTAH,VERY LOW
1626871,0,1,2016,0o1014,YORK,MEDIUM
1626872,1,0,2016,0o1010,CAROLINA,VERY LOW
1626873,0,0,2016,0o1400,JERSEY,LOW
1626874,0,1,2012,0o1400,COLUMBIA,MEDIUM
1626875,0,1,2012,0o1424,CAROLINA,HIGH
1626876,0,0,2016,0o1021,CALIFORNIA,LOW
1626877,0,0,2016,0o1404,MINNESOTA,LOW
1626878,0,1,2016,0o1400,MARYLAND,MEDIUM
1626879,0,1,2014,0o1404,MICHIGAN,LOW
1626880,0,1,2015,0o1021,CAROLINA,VERY LOW
1626881,0,1,2015,0o1004,PENNSYLVANIA,VERY LOW
1626882,0,1,2015,0o1012,YORK,MEDIUM
1626883,0,1,2012,0o1044,CALIFORNIA,LOW
1626884,0,1,2012,0o1300,TEXAS,VERY LOW
1626885,0,1,2015,0o1400,ARIZONA,LOW
1626886,0,1,2016,0o1400,CAROLINA,MEDIUM

In [45]:
soccode_ratio_mapping

{'0o0': 0.10145240667386868,
 '0o1001': 0.24,
 '0o1002': 0.06399630155532808,
 '0o1003': 0.0,
 '0o1004': 0.05390502751668565,
 '0o1005': 0.0,
 '0o1010': 0.08691503484898773,
 '0o1020': 0.049732056772573384,
 '0o1021': 0.0,
 '0o1022': 0.28708133971291866,
 '0o1024': 0.20481927710843373,
 '0o1030': 0.04521052398065576,
 '0o1040': 0.07875569588461125,
 '0o1044': 0.034114403859407304,
 '0o1050': 0.03572679509632224,
 '0o1100': 0.03887808211976237,
 '0o1104': 0.07335127860026917,
 '0o1110': 0.0,
 '0o1120': 0.032944406314344546,
 '0o1140': 0.048218029350104816,
 '0o1200': 0.07001464543865453,
 '0o1204': 0.0707482993197279,
 '0o1220': 0.5,
 '0o1240': 0.03571428571428571,
 '0o1300': 0.03133435042835348,
 '0o1304': 0.062124592414621586,
 '0o1340': 0.0783132530120482,
 '0o1400': 0.01820930665367396,
 '0o1402': 0.034883720930232565,
 '0o1403': 0.0,
 '0o1404': 0.037085084669537985,
 '0o1420': 0.1171615076858286,
 '0o1422': 0.07972367438386856,
 '0o1424': 0.03910558000708251,
 '0o1430': 0.10569785676947203,
 '0o1440': 0.0409612233752048,
 '0o1514': 0.0283498261567264,
 '0o1520': 0.045454545454545456,
 '0o1600': 0.17391304347826084,
 '0o1620': 0.12021466905187835}

In [51]:
df_soccode_ratio.sort_values('ratio_soc')

          ratio_soc
SOC_CODE
0o1003     0.000000
0o1005     0.000000
0o1021     0.000000
0o1110     0.000000
0o1403     0.000000
0o1400     0.018209
0o1514     0.028350
0o1300     0.031334
0o1120     0.032944
0o1044     0.034114
0o1402     0.034884
0o1240     0.035714
0o1050     0.035727
0o1404     0.037085
0o1100     0.038878
0o1424     0.039106
0o1440     0.040961
0o1030     0.045211
0o1520     0.045455
0o1140     0.048218
0o1020     0.049732
0o1004     0.053905
0o1304     0.062125
0o1002     0.063996
0o1200     0.070015
0o1204     0.070748
0o1104     0.073351
0o1340     0.078313
0o1040     0.078756
0o1422     0.079724
0o1010     0.086915
0o0        0.101452
0o1430     0.105698
0o1420     0.117162
0o1620     0.120215
0o1600     0.173913
0o1024     0.204819
0o1001     0.240000
0o1022     0.287081
0o1220     0.500000