In [20]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import scale

In [83]:
file_path='./datas/'
file_name=file_path+"h1b_train_preprocessing.csv"
df=pd.read_csv(file_name,keep_default_na=False)
df.columns

Index(['CASE_STATUS', 'EMPLOYER_NAME', 'SOC_NAME', 'JOB_TITLE',
       'FULL_TIME_POSITION', 'PREVAILING_WAGE', 'YEAR', 'WORKSITE', 'lon',
       'lat', 'ID', 'SOC_CODE', 'STATE'],
      dtype='object')

In [84]:
df['ID']=df["ID"].map(lambda x : x[2:])

TypeError: 'int' object is not subscriptable

In [85]:
df['ID']=df["ID"].map(lambda x : int(x))

In [86]:
df=df.sort_values("ID")

In [87]:
df

,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE,lon,lat,ID,SOC_CODE,STATE
0,0,"INTERNATIONAL SYSTEMS TECHNOLOGIES, INC.",Computer Programmers,PROGRAMMER ANALYST,1,61589.0,2014,"SUNNYVALE, CALIFORNIA",-122.03634960000001,37.368829999999996,0,0o1400,CALIFORNIA
1,0,GOOGLE INC.,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,SITE RELIABILITY ENGINEER,1,79144.0,2015,"SAN FRANCISCO, CALIFORNIA",-122.4194155,37.7749295,1,0o1400,CALIFORNIA
2,0,WIPRO LIMITED,"Computer Occupations, All Other",PROJECT MANAGER,1,73882.0,2014,"EL SEGUNDO, CALIFORNIA",-118.4164652,33.9191799,2,0o1400,CALIFORNIA
3,0,"CPO SERVICES, INC.",Orthotists and Prosthetists,STAFF PROSTHETIST,1,61589.0,2011,"PEORIA, ILLINOIS",-89.58898640000002,40.6936488,3,0o0,ILLINOIS
4,1,"UNIVERSITY OF CALIFORNIA, SAN DIEGO","MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",ASSISTANT PROJECT SCIENTIST,1,42120.0,2015,"LA JOLLA, CALIFORNIA",-117.2712717,32.832811199999995,5,0o1200,CALIFORNIA
5,0,GOOGLE INC.,"Computer Software Engineers, Applications",SOFTWARE ENGINEER,1,82035.0,2011,"MOUNTAIN VIEW, CALIFORNIA",-122.08385109999999,37.3860517,6,0o1400,CALIFORNIA
6,0,"COMPREHAB, INC.",PHYSICAL THERAPISTS,PHYSICAL THERAPIST,0,64168.0,2016,"GASTONIA, NORTH CAROLINA",-81.1873005,35.262082,7,0o1200,CAROLINA
7,0,JPMORGAN CHASE AND CO.,"Software Developers, Applications",APPLICATIONS DEVELOPER,1,92726.0,2012,"COLUMBUS, OHIO",-82.9987942,39.9611755,8,0o1400,OHIO
8,0,"IRONBRIDGE CONSULTING, LLC","Information Security Analysts, Web Developers,...",SOFTWARE ENGINEER/ NETWORK ANALYST,1,57866.0,2011,"ARLINGTON, VIRGINIA",-77.1067698,38.879969700000004,9,0o1400,VIRGINIA
9,0,"AXON SOLUTIONS, INC.",Computer Systems Analysts,MANAGING CONSULTANT,1,91998.0,2014,"UNIVERSAL CITY, CALIFORNIA",-118.3505779,34.1397694,10,0o1400,CALIFORNIA
10,0,MICROSOFT CORPORATION,"Software Developers, Applications",SOFTWARE DEVELOPMENT ENGINEER IN TEST,1,86278.0,2013,"REDMOND, WASHINGTON",-122.12151200000001,47.6739881,11,0o1400,WASHINGTON
11,0,MOBILE IRON INC.,"Software Developers, Systems Software",SYSTEMS ENGINEER,1,103709.0,2012,"MOUNTAIN VIEW, CALIFORNIA",-122.08385109999999,37.3860517,12,0o1400,CALIFORNIA
12,0,"TECHNIP USA, INC.",Chemical Engineers,FACILITIES SPECIALIST,1,75298.0,2014,"HOUSTON, TEXAS",-95.36980279999999,29.7604267,13,0o1100,TEXAS
13,0,"COMMVAULT AMERICAS, INC.",Computer Systems Analysts,SYSTEM TESTER,1,74651.0,2013,"OCEANPORT, NEW JERSEY",-74.0151382,40.318166299999994,14,0o1400,JERSEY
14,0,CUMMINS INC.,Mechanical Engineers,SENIOR MECHANICAL ENGINEER - PERFORMANCE IMPRO...,1,66019.0,2011,"FRIDLEY, MINNESOTA",-93.2632821,45.086076500000004,15,0o1100,MINNESOTA
15,0,"PACIFIC INVESTMENT MANAGEMENT COMPANY, LLC","Securities, Commodities, and Financial Service...","VICE PRESIDENT, PORTFOLIO MANAGER",1,57949.0,2014,"NEWPORT BEACH, CALIFORNIA",-117.9289469,33.6189101,16,0o1400,CALIFORNIA
16,0,UNIVERSITY OF TEXAS HEALTH SCIENCE CENTER AT S...,"HEALTH SPECIALTIES TEACHERS, POSTSECONDARY",ASSISTANT PROFESSOR,1,96277.0,2015,"SAN ANTONIO, TEXAS",-98.4936282,29.4241219,17,0o1200,TEXAS
17,0,"HARTE-HANKS DATA TECHNOLOGIES, INC.",Marketing Managers,ASSOCIATE PRODUCT MANAGER,1,55931.0,2011,"LINTHICUM HEIGHTS, MARYLAND",-76.65274559999997,39.205107700000006,18,0o1400,MARYLAND
18,0,LENORA SYSTEMS INC,Computer Systems Analysts,PROGRAMMER ANALYST,1,57075.0,2014,"DALLAS, TEXAS",-96.7969879,32.7766642,19,0o1400,TEXAS
19,0,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYST,TECHNOLOGY LEAD - US,1,89149.0,2016,"SUNNYVALE, CALIFORNIA",-122.03634960000001,37.368829999999996,20,0o1400,CALIFORNIA
20,0,HITACHI CONSULTING CORPORATION,"Software Developers, Applications",SOFTWARE ENGINEER,1,73174.0,2013,"REDMOND, WASHINGTON",-122.12151200000001,47.6739881,21,0o1400,WASHINGTON
21,0,INFOSYS LIMITED,Computer Systems Analysts,PROJECT LEAD,1,76315.0,2012,"TAMPA, FLORIDA",-82.4571776,27.950575,22,0o1400,FLORIDA
22,0,"FORTINET, INC.","COMPUTER OCCUPATIONS, ALL OTHER",CARRIER READINESS TEST ENGINEER,1,77563.0,2015,"SUNNYVALE, CALIFORNIA",-122.03634960000001,37.368829999999996,24,0o1400,CALIFORNIA
23,0,"INDEED, INC.",MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,ONLINE MARKET ANALYST,0,60258.0,2016,"AUSTIN, TEXAS",-97.7430608,30.267153000000004,25,0o1010,TEXAS
24,0,"CAZARCH, INC.",Architectural and Civil Drafters,ARCHITETURAL DESIGNER,1,40685.0,2013,"BROOKLYN, NEW YORK",-73.94415790000002,40.6781784,26,0o1100,YORK
25,0,CREDIT SUISSE SECURITIES (USA) LLC,Accountants and Auditors,EXEMPT NON-OFFICER,1,55370.0,2013,"NEW YORK, NEW YORK",-74.00594129999998,40.7127837,27,0o1010,YORK
26,0,"JCG TECHNOLOGIES, INC.",Computer Programmers,COMPUTER PROGRAMMER,1,67995.0,2011,"WESTBOROUGH, MASSACHUSETTS",-71.6161294,42.269521600000004,28,0o1400,MASSACHUSETTS
27,1,APERI CORPORATION,COMPUTER HARDWARE ENGINEERS,SYSTEMS ENGINEER,1,66200.0,2015,"CAMARILLO, CALIFORNIA",-119.0376023,34.216393700000005,29,0o1400,CALIFORNIA
28,0,"UPMC EMERGENCY MEDICINE, INC.","Physicians and Surgeons, All Other",HOSPITALIST,1,81994.0,2012,"GREENVILLE, PENNSYLVANIA",-80.39117850000002,41.404499,30,0o1200,PENNSYLVANIA
29,0,DELOITTE CONSULTING LLP,Computer Systems Analysts,CONSULTANT,1,75899.0,2014,"BALA CYNWYD, PENNSYLVANIA",-75.23040379999998,40.01314179999999,31,0o1400,PENNSYLVANIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626857,0,ERNST & YOUNG U.S. LLP,Management Analysts,TAS SENIOR,1,93538.0,2014,"SAN FRANCISCO, CALIFORNIA",-122.4194155,37.7749295,1802423,0o1020,CALIFORNIA
1626858,0,HYUNDAI DYMOS GEORGIA LLC,Financial Analysts,FINANCIAL SPECIALIST,1,49088.0,2014,"WEST POINT, GEORGIA",-85.18327459999998,32.877905600000005,1802424,0o1002,GEORGIA
1626859,0,TRUSTEK INC.,Database Administrators,SQL SERVER DBA,1,60154.0,2012,"SOUTH PLAINFIELD, NEW JERSEY",-74.4115401,40.5792701,1802425,0o1400,JERSEY
1626860,0,TATA CONSULTANCY SERVICES LIMITED,COMPUTER SYSTEMS ANALYSTS,ANALYST,1,41163.0,2015,"SAN JUAN, PUERTO RICO",-66.1057355,18.465539399999997,1802426,0o1400,RICO
1626861,0,MICROSOFT CORPORATION,"SOFTWARE DEVELOPERS, APPLICATIONS",SOFTWARE ENGINEER,1,101088.0,2016,"REDMOND, WASHINGTON",-122.12151200000001,47.6739881,1802427,0o1400,WASHINGTON
1626862,0,"TECH MAHINDRA ( AMERICAS), INC","Computer Occupations, All Other",SOFTWARE TEST ENGINEER,1,77938.0,2014,"RICHARDSON, TEXAS",-96.72985190000001,32.948333500000004,1802428,0o1400,TEXAS
1626863,0,RESOURCESOFT INC,Database Administrators,DATABASE ADMINISTRATOR,1,53498.0,2012,"BOSTON, MASSACHUSETTS",-71.0588801,42.360082500000004,1802429,0o1400,MASSACHUSETTS
1626864,0,KANSAS STATE UNIVERSITY,"Biological Scientists, All Other",WEB/DATABASE DEVELOPER,1,40706.0,2014,"MANHATTAN, KANSAS",-96.5716694,39.1836082,1802430,0o1004,KANSAS
1626865,0,IREDELL-STATESVILLE SCHOOLS,"Middle School Teachers, Except Special and Voc...",ESL TEACHER,1,37987.0,2011,"TROUTMAN, NORTH CAROLINA",,,1802431,0o1040,CAROLINA
1626866,0,WIPRO LIMITED,"COMPUTER OCCUPATIONS, ALL OTHER",TEST ENGINEER LEVEL 1,1,60528.0,2015,"PALO ALTO, CALIFORNIA",-122.14301950000001,37.441883399999995,1802433,0o1400,CALIFORNIA
1626867,0,WIPRO LIMITED,"Computer Occupations, All Other",LEAD ENGINEER,1,62878.0,2014,"WILMINGTON, DELAWARE",-75.5397878,39.7390721,1802435,0o1400,DELAWARE
1626868,0,SCINTILLA SOFT INC,COMPUTER PROGRAMMERS,PROGRAMMER ANALYST,0,54850.0,2016,"LOS ANGELES, CALIFORNIA",-118.24368490000002,34.0522342,1802436,0o1400,CALIFORNIA
1626869,0,GLOBAL TECHNICAL SOFTWARE SERVICES INC,Computer Systems Analysts,SYSTEMS ANALYST,1,65416.0,2014,"AKRON, OHIO",-81.51900529999998,41.08144470000001,1802437,0o1400,OHIO
1626870,0,BRIGHAM YOUNG UNIVERSITY,Chemists,POST DOCTORAL RESEARCH ASSISTANT IN CHEMISTRY,1,35298.0,2011,"PROVO, UTAH",-111.6585337,40.233843799999995,1802438,0o1004,UTAH
1626871,0,HEADSTRONG SERVICES LLC,SALES ENGINEERS,BUSINESS DEVELOPMENT MANAGER,1,86986.0,2016,"NEW YORK, NEW YORK",-74.00594129999998,40.7127837,1802439,0o1100,YORK
1626872,1,ROBERTSON IMMIGRATION LAW FIRM,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,MARKETING SPECIALIST,0,37752.0,2016,"RALEIGH, NORTH CAROLINA",-78.6381787,35.7795897,1802441,0o1010,CAROLINA
1626873,0,"3I INFOTECH, INC.",COMPUTER PROGRAMMERS,PROGRAMMER ANALYST,0,51730.0,2016,"EDISON, NEW JERSEY",-74.4120953,40.5187154,1802442,0o1400,JERSEY
1626874,0,"INTERNATIONAL TECHNOLOGIES PRO, LLC","Software Developers, Applications",QA SPECIALIST,1,70491.0,2012,"WASHINGTON, DISTRICT OF COLUMBIA",-77.03687070000002,38.9071923,1802443,0o1400,COLUMBIA
1626875,0,CAPGEMINI FINANCIAL SERVICES USA INC,Computer and Information Systems Managers,MANAGER,1,91270.0,2012,"CHARLOTTE, NORTH CAROLINA",-80.8431267,35.2270869,1802444,0o1400,CAROLINA
1626876,0,"ROD CAPITAL MANAGEMENT, LLC",MANAGEMENT ANALYSTS,OPERATIONS ANALYST,0,56035.0,2016,"VENICE, CALIFORNIA",-118.4694832,33.9850469,1802445,0o1020,CALIFORNIA
1626877,0,LARSEN & TOUBRO INFOTECH LIMITED,COMPUTER SYSTEMS ENGINEERS,COMPUTER SYSTEMS ENGINEER,0,63856.0,2016,"ST. PAUL, MINNESOTA",-93.0899578,44.953702899999996,1802447,0o1400,MINNESOTA
1626878,0,"DVR SOFTEK, INC",COMPUTER PROGRAMMERS,PROGRAMMER ANALYST,1,73632.0,2016,"OWINGS MILLS, MARYLAND",-76.7802528,39.4195499,1802448,0o1400,MARYLAND
1626879,0,UST GLOBAL INC,Commercial and Industrial Designers,ENGINEERING LEAD-MECHANICAL,1,51542.0,2014,"SOUTHFIELD, MICHIGAN",-83.2218731,42.473368799999996,1802449,0o1400,MICHIGAN
1626880,0,"LANCESOFT, INC.",MANAGEMENT ANALYSTS,BUSINESS SYSTEM ANALYST,1,42661.0,2015,"CHARLOTTE, NORTH CAROLINA",-80.8431267,35.2270869,1802450,0o1020,CAROLINA
1626881,0,"VARENHORST ARCHITECTS, PC",ARCHITECTURAL AND CIVIL DRAFTERS,ARCHITECTURAL DRAFTER,1,33051.0,2015,"PHILADELPHIA, PENNSYLVANIA",-75.1652215,39.9525839,1802451,0o1100,PENNSYLVANIA
1626882,0,DELOITTE TAX LLP,ACCOUNTANTS AND AUDITORS,TAX SENIOR,1,74110.0,2015,"NEW YORK, NEW YORK",-74.00594129999998,40.7127837,1802452,0o1010,YORK
1626883,0,"UNIVERSITY OF CALIFORNIA, SAN DIEGO","Engineering Teachers, Postsecondary",ASSISTANT PROFESSOR,1,67530.0,2012,"LA JOLLA, CALIFORNIA",-117.2712717,32.832811199999995,1802453,0o1100,CALIFORNIA
1626884,0,UNIVERSITY OF TEXAS HEALTH SCIENCE CENTER AT S...,"Medical Scientists, Except Epidemiologists",POSTDOCTORAL RESEARCH FELLOW,1,34382.0,2012,"SAN ANTONIO, TEXAS",-98.4936282,29.4241219,1802455,0o1200,TEXAS
1626885,0,SYNTEL INC,COMPUTER SYSTEMS ANALYSTS,PROGRAMMER ANALYST,1,58677.0,2015,"SCOTTSDALE, ARIZONA",-111.9260519,33.494170399999994,1802456,0o1400,ARIZONA
1626886,0,REED ELSEVIER INC. (LEXISNEXIS DIVISION),"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",SOFTWARE ENGINEER III,1,88005.0,2016,"RALEIGH, NORTH CAROLINA",-78.6381787,35.7795897,1802457,0o1400,CAROLINA

In [88]:
#df=df.drop("ID",axis=1)
df=df.drop("EMPLOYER_NAME",axis=1)
df=df.drop("SOC_NAME",axis=1)
df=df.drop("JOB_TITLE",axis=1)
df=df.drop("WORKSITE",axis=1)
df=df.drop("lon",axis=1)
df=df.drop("lat",axis=1)

In [89]:
df.PREVAILING_WAGE=scale(df.PREVAILING_WAGE)

In [90]:
df.isnull().sum()

CASE_STATUS           0
FULL_TIME_POSITION    0
PREVAILING_WAGE       0
YEAR                  0
ID                    0
SOC_CODE              0
STATE                 0
dtype: int64

In [91]:
save_file=file_path+'h1b_train_final_data_ry.csv'
df.to_csv(save_file,index=False)

In [92]:
df

,CASE_STATUS,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,ID,SOC_CODE,STATE
0,0,1,-0.024961,2014,0,0o1400,CALIFORNIA
1,0,1,-0.019911,2015,1,0o1400,CALIFORNIA
2,0,1,-0.021425,2014,2,0o1400,CALIFORNIA
3,0,1,-0.024961,2011,3,0o0,ILLINOIS
4,1,1,-0.030562,2015,5,0o1200,CALIFORNIA
5,0,1,-0.019080,2011,6,0o1400,CALIFORNIA
6,0,0,-0.024219,2016,7,0o1200,CAROLINA
7,0,1,-0.016004,2012,8,0o1400,OHIO
8,0,1,-0.026032,2011,9,0o1400,VIRGINIA
9,0,1,-0.016214,2014,10,0o1400,CALIFORNIA
10,0,1,-0.017859,2013,11,0o1400,WASHINGTON
11,0,1,-0.012845,2012,12,0o1400,CALIFORNIA
12,0,1,-0.021018,2014,13,0o1100,TEXAS
13,0,1,-0.021204,2013,14,0o1400,JERSEY
14,0,1,-0.023687,2011,15,0o1100,MINNESOTA
15,0,1,-0.026008,2014,16,0o1400,CALIFORNIA
16,0,1,-0.014983,2015,17,0o1200,TEXAS
17,0,1,-0.026589,2011,18,0o1400,MARYLAND
18,0,1,-0.026260,2014,19,0o1400,TEXAS
19,0,1,-0.017033,2016,20,0o1400,CALIFORNIA
20,0,1,-0.021629,2013,21,0o1400,WASHINGTON
21,0,1,-0.020725,2012,22,0o1400,FLORIDA
22,0,1,-0.020366,2015,24,0o1400,CALIFORNIA
23,0,0,-0.025344,2016,25,0o1010,TEXAS
24,0,1,-0.030975,2013,26,0o1100,YORK
25,0,1,-0.026750,2013,27,0o1010,YORK
26,0,1,-0.023118,2011,28,0o1400,MASSACHUSETTS
27,1,1,-0.023635,2015,29,0o1400,CALIFORNIA
28,0,1,-0.019091,2012,30,0o1200,PENNSYLVANIA
29,0,1,-0.020845,2014,31,0o1400,PENNSYLVANIA
...,...,...,...,...,...,...,...
1626857,0,1,-0.015771,2014,1802423,0o1020,CALIFORNIA
1626858,0,1,-0.028557,2014,1802424,0o1002,GEORGIA
1626859,0,1,-0.025374,2012,1802425,0o1400,JERSEY
1626860,0,1,-0.030837,2015,1802426,0o1400,RICO
1626861,0,1,-0.013599,2016,1802427,0o1400,WASHINGTON
1626862,0,1,-0.020258,2014,1802428,0o1400,TEXAS
1626863,0,1,-0.027289,2012,1802429,0o1400,MASSACHUSETTS
1626864,0,1,-0.030969,2014,1802430,0o1004,KANSAS
1626865,0,1,-0.031751,2011,1802431,0o1040,CAROLINA
1626866,0,1,-0.025266,2015,1802433,0o1400,CALIFORNIA
1626867,0,1,-0.024590,2014,1802435,0o1400,DELAWARE
1626868,0,0,-0.026900,2016,1802436,0o1400,CALIFORNIA
1626869,0,1,-0.023860,2014,1802437,0o1400,OHIO
1626870,0,1,-0.032524,2011,1802438,0o1004,UTAH
1626871,0,1,-0.017655,2016,1802439,0o1100,YORK
1626872,1,0,-0.031818,2016,1802441,0o1010,CAROLINA
1626873,0,0,-0.027797,2016,1802442,0o1400,JERSEY
1626874,0,1,-0.022400,2012,1802443,0o1400,COLUMBIA
1626875,0,1,-0.016423,2012,1802444,0o1400,CAROLINA
1626876,0,0,-0.026559,2016,1802445,0o1020,CALIFORNIA
1626877,0,0,-0.024309,2016,1802447,0o1400,MINNESOTA
1626878,0,1,-0.021497,2016,1802448,0o1400,MARYLAND
1626879,0,1,-0.027851,2014,1802449,0o1400,MICHIGAN
1626880,0,1,-0.030406,2015,1802450,0o1020,CAROLINA
1626881,0,1,-0.033171,2015,1802451,0o1100,PENNSYLVANIA
1626882,0,1,-0.021359,2015,1802452,0o1010,YORK
1626883,0,1,-0.023252,2012,1802453,0o1100,CALIFORNIA
1626884,0,1,-0.032788,2012,1802455,0o1200,TEXAS
1626885,0,1,-0.025799,2015,1802456,0o1400,ARIZONA
1626886,0,1,-0.017362,2016,1802457,0o1400,CAROLINA