In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from statistics import mode
import re
from xgboost import XGBClassifier

In [2]:
file_path='./datas/'
file_name=file_path+"h1b_dev_preprocessing.csv"
df=pd.read_csv(file_name,keep_default_na=False)
df.columns

Index(['CASE_STATUS', 'FULL_TIME_POSITION', 'PREVAILING_WAGE', 'YEAR',
       'SOC_CODE', 'STATE'],
      dtype='object')

In [3]:
df[df.STATE.isna()]

Empty DataFrame
Columns: [CASE_STATUS, FULL_TIME_POSITION, PREVAILING_WAGE, YEAR, SOC_CODE, STATE]
Index: []

In [4]:
df

,CASE_STATUS,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,SOC_CODE,STATE
0,0,Y,54496.0,2013.0,0o1400,TEXAS
1,0,Y,62046.0,2015.0,0o1400,TEXAS
2,0,N,97635.2,2014.0,0o1200,OHIO
3,0,Y,101130.0,2014.0,0o1200,ILLINOIS
4,0,Y,75982.0,2014.0,0o1400,MASSACHUSETTS
5,0,Y,67038.0,2013.0,0o1400,MINNESOTA
6,0,Y,50461.0,2012.0,0o1300,WISCONSIN
7,0,Y,74214.0,2016.0,0o1400,MASSACHUSETTS
8,0,Y,48400.0,2012.0,0o1004,CALIFORNIA
9,0,Y,48430.0,2013.0,0o1050,WISCONSIN
10,0,Y,57179.0,2012.0,0o1400,JERSEY
11,0,Y,109429.0,2016.0,0o1420,TEXAS
12,0,Y,66830.0,2012.0,0o1400,WISCONSIN
13,0,Y,73112.0,2015.0,0o1400,KANSAS
14,0,Y,73923.0,2015.0,0o1400,CALIFORNIA
15,0,Y,95326.0,2015.0,0o1004,OREGON
16,0,Y,83408.0,2014.0,0o1400,MARYLAND
17,0,Y,56160.0,2014.0,0o1400,OHIO
18,0,N,52686.0,2016.0,0o1400,CAROLINA
19,0,Y,68411.0,2014.0,0o1400,CAROLINA
20,0,Y,80725.0,2012.0,0o1400,UTAH
21,0,Y,41808.0,2014.0,0o1300,TEXAS
22,0,Y,72717.0,2016.0,0o1400,TEXAS
23,0,Y,76898.0,2015.0,0o1420,YORK
24,0,Y,50814.0,2014.0,0o1400,CONNECTICUT
25,0,Y,67725.0,2012.0,0o1404,CALIFORNIA
26,0,Y,47632.0,2015.0,0o1400,CONNECTICUT
27,0,Y,40980.0,2015.0,0o1040,GEORGIA
28,0,Y,59280.0,2015.0,0o1400,PENNSYLVANIA
29,0,Y,71510.0,2014.0,0o1400,JERSEY
...,...,...,...,...,...,...
541492,0,Y,62566.0,2015.0,0o1400,TEXAS
541493,0,Y,56888.0,2011.0,0o1004,MICHIGAN
541494,0,Y,81037.0,2016.0,0o1404,MINNESOTA
541495,0,Y,58531.0,2013.0,0o1100,HAMPSHIRE
541496,0,Y,71718.0,2016.0,0o1400,PENNSYLVANIA
541497,0,Y,51210.0,2014.0,0o1400,CAROLINA
541498,0,Y,42037.0,2012.0,0o1300,TEXAS
541499,1,Y,60300.0,2011.0,0o1404,MASSACHUSETTS
541500,0,Y,61901.0,2015.0,0o1400,MICHIGAN
541501,0,Y,64792.0,2015.0,0o1004,VIRGINIA
541502,0,Y,71906.0,2015.0,0o1021,JERSEY
541503,0,Y,65832.0,2011.0,0o1404,COLORADO
541504,0,N,52374.0,2016.0,0o1400,OHIO
541505,0,Y,82202.0,2015.0,0o1400,WASHINGTON
541506,0,Y,82243.0,2012.0,0o1020,YORK
541507,0,Y,55245.0,2014.0,0o1400,CALIFORNIA
541508,0,Y,53019.0,2013.0,0o1404,PENNSYLVANIA
541509,0,Y,43160.0,2015.0,0o1105,CALIFORNIA
541510,0,Y,48963.0,2011.0,0o1012,COLUMBIA
541511,0,Y,61318.0,2014.0,0o1400,ILLINOIS
541512,0,Y,83844.8,2016.0,0o1200,JERSEY
541513,0,Y,50211.0,2013.0,0o1400,ILLINOIS
541514,0,Y,74422.0,2012.0,0o1400,JERSEY
541515,0,Y,55162.0,2012.0,0o1400,CALIFORNIA
541516,0,Y,94786.0,2015.0,0o1100,CALIFORNIA
541517,0,Y,82701.0,2014.0,0o1400,WASHINGTON
541518,1,N,64563.2,2016.0,0o1010,CALIFORNIA
541519,0,Y,97594.0,2015.0,0o1400,CALIFORNIA
541520,1,Y,42765.0,2012.0,0o1005,YORK
541521,0,Y,90813.0,2016.0,0o1400,YORK

In [5]:
df[['CASE_STATUS', 'FULL_TIME_POSITION', 'YEAR','SOC_CODE', 'STATE']]=df[['CASE_STATUS', 'FULL_TIME_POSITION', 'YEAR','SOC_CODE', 'STATE']].apply(lambda x : x.astype('category'))

In [8]:
X = df.drop('CASE_STATUS', axis=1)
y = df.CASE_STATUS
seed = 6
test_size = 0.40
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)
X_train.columns

Index(['FULL_TIME_POSITION', 'PREVAILING_WAGE', 'YEAR', 'SOC_CODE', 'STATE'], dtype='object')

In [9]:
X_train_encode = pd.get_dummies(X_train)
X_test_encode = pd.get_dummies(X_test)

In [10]:
train_X = X_train_encode.as_matrix()
train_y = y_train.as_matrix()

c:\users\adboy\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
c:\users\adboy\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

In [11]:
gbm=XGBClassifier(max_features='sqrt', subsample=0.8, random_state=10)

In [12]:
from sklearn.model_selection import GridSearchCV

In [13]:
parameters = [{'n_estimators': [10, 100]},
              {'learning_rate': [0.1, 0.01, 0.5]}]

In [14]:
grid_search = GridSearchCV(estimator = gbm, param_grid = parameters, scoring='accuracy', cv = 3, n_jobs=-1)

In [15]:
grid_search = grid_search.fit(train_X, train_y)

In [16]:
grid_search.grid_scores_, grid_search.best_params_, grid_search.best_score_

c:\users\adboy\appdata\local\programs\python\python36\lib\site-packages\sklearn\model_selection\_search.py:762: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)

([mean: 0.96614, std: 0.00006, params: {'n_estimators': 10},
  mean: 0.96621, std: 0.00008, params: {'n_estimators': 100},
  mean: 0.96621, std: 0.00008, params: {'learning_rate': 0.1},
  mean: 0.96617, std: 0.00007, params: {'learning_rate': 0.01},
  mean: 0.96612, std: 0.00010, params: {'learning_rate': 0.5}],
 {'n_estimators': 100},
 0.9662094160590681)

In [17]:
grid_search.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, max_features='sqrt', min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=10, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=True,
       subsample=0.8)

In [18]:
gbm=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.5, max_delta_step=0,
       max_depth=3, max_features='sqrt', min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=10, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=True,
       subsample=0.8).fit(train_X, train_y)

In [19]:
y_pred = gbm.predict(X_test_encode.as_matrix())

c:\users\adboy\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
c:\users\adboy\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [20]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[208927     61]
 [  7389    232]]
             precision    recall  f1-score   support

          0       0.97      1.00      0.98    208988
          1       0.79      0.03      0.06      7621

avg / total       0.96      0.97      0.95    216609